#!/usr/bin/env python3
"""
Regenerate the Summary section of conformance/COVERAGE.md from the live
JSON fixture files. The Summary section lists per-layer file and case
counts; this script treats the fixture tree as source of truth and keeps
the table in sync, avoiding the kind of drift that previously accumulated
(respondent listed as "Forthcoming" despite having fixtures, composed
layer counts going stale, etc.).

Stops at the first "---" line after the "## Summary" heading. Everything
else in COVERAGE.md is preserved byte-for-byte.

Exit status:
  0  -- Summary was already up to date, or rewrite succeeded.
  1  -- COVERAGE.md not found or malformed (no Summary section).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DSL_ROOT = SCRIPT_DIR.parent
CONFORMANCE = DSL_ROOT / "conformance"
COVERAGE_MD = CONFORMANCE / "COVERAGE.md"


# Layer label -> (relative path, recurse_subdirs_to_exclude_from_parent)
# Order matches the existing Summary table.
LAYERS: list[tuple[str, str, list[str]]] = [
    ("Foundations", "foundations", []),
    ("Operant", "operant", ["stateful", "trial-based"]),
    ("Operant-Stateful", "operant/stateful", []),
    ("Operant-Trial-Based", "operant/trial-based", []),
    ("Respondent", "respondent", []),
    ("Composed", "composed", []),
    ("Experiment", "experiment", []),
    ("Annotations", "annotations", []),
    ("Representations (T-τ)", "representations/t-tau", []),
]


def count_layer(rel_path: str, exclude: list[str]) -> tuple[int, int]:
    """Return (file_count, case_count) for a layer directory."""
    layer_dir = CONFORMANCE / rel_path
    if not layer_dir.is_dir():
        return 0, 0

    files = 0
    cases = 0
    excluded_dirs = {layer_dir / sub for sub in exclude}

    for path in sorted(layer_dir.rglob("*.json")):
        if any(str(path).startswith(str(ex) + "/") for ex in excluded_dirs):
            continue
        if rel_path == "annotations" and "extensions" in path.parts:
            # annotations/extensions/ is rolled up into the Annotations row
            # per the original Summary convention.
            pass
        files += 1
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            print(f"[warn] could not parse {path}", file=sys.stderr)
            continue
        if isinstance(data, list):
            cases += len(data)
    return files, cases


def status_for(label: str, files: int, cases: int) -> str:
    if files == 0:
        if label == "Foundations":
            return "Forthcoming (paradigm-neutral lexical fixtures)"
        if label == "Respondent":
            return "Forthcoming (Tier A primitive fixtures)"
        if label == "Composed":
            return "Forthcoming (CER / PIT / autoshape / omission / two-process)"
        return "Forthcoming"
    if label == "Operant":
        return "✅ Primary coverage"
    if label == "Annotations":
        return "✅ Full coverage (incl. respondent-annotator extension stub)"
    return "✅ Full coverage"


def build_summary_block() -> str:
    rows: list[tuple[str, int, int]] = []
    for label, rel, exclude in LAYERS:
        files, cases = count_layer(rel, exclude)
        rows.append((label, files, cases))

    total_files = sum(f for _, f, _ in rows)
    total_cases = sum(c for _, _, c in rows)

    lines = [
        "## Summary",
        "",
        "<!-- GENERATED by scripts/sync-conformance-counts.py — do not edit by hand. -->",
        "",
        "| Layer | Files | Test Cases | Status |",
        "|---|---|---|---|",
    ]
    for label, files, cases in rows:
        lines.append(
            f"| **{label}** | {files} | {cases} | {status_for(label, files, cases)} |"
        )
    lines.append(f"| **Total** | **{total_files}** | **{total_cases}** | |")
    lines.append("")
    return "\n".join(lines)


def rewrite_coverage() -> int:
    if not COVERAGE_MD.is_file():
        print(f"[error] {COVERAGE_MD} not found", file=sys.stderr)
        return 1

    text = COVERAGE_MD.read_text(encoding="utf-8")
    start_marker = "## Summary"
    end_marker = "---"

    start = text.find(start_marker)
    if start < 0:
        print("[error] '## Summary' section not found", file=sys.stderr)
        return 1

    end = text.find(f"\n{end_marker}", start)
    if end < 0:
        print("[error] end-of-Summary marker '---' not found", file=sys.stderr)
        return 1

    new_summary = build_summary_block()
    new_text = text[:start] + new_summary + "\n" + text[end + 1 :]

    if new_text == text:
        return 0

    COVERAGE_MD.write_text(new_text, encoding="utf-8")
    print(f"[sync] updated {COVERAGE_MD.relative_to(DSL_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(rewrite_coverage())
